# Generated by Django 4.2.7 on 2024-02-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_text', models.CharField(max_length=80)),
                ('button_label', models.CharField(max_length=40)),
                ('background_image_url', models.CharField(max_length=2083)),
            ],
        ),
    ]
