# Generated by Django 4.2.7 on 2025-04-03 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_leidinglid_speltak_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media_title', models.CharField(max_length=50)),
                ('social_media_paragraph_text', models.CharField(max_length=1000)),
                ('facebook_button_label', models.CharField(max_length=50)),
                ('instagram_button_label', models.CharField(max_length=50)),
                ('contact_verhuur_title', models.CharField(max_length=50)),
                ('contact_verhuur_paragraph_text', models.CharField(max_length=1000)),
                ('contact_button_label', models.CharField(max_length=50)),
                ('verhuur_button_label', models.CharField(max_length=50)),
                ('vrienden_title', models.CharField(max_length=50)),
                ('vrienden_paragraph_text', models.CharField(max_length=1000)),
                ('vrienden_button_label', models.CharField(max_length=50)),
                ('documenten_title', models.CharField(max_length=50)),
                ('huishoudelijk_regelement_button_label', models.CharField(max_length=50)),
                ('privacybeleid_button_label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HuurInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('paragraph_text', models.CharField(max_length=1000)),
                ('button_label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ScoutingAppInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image_caption', models.CharField(max_length=100)),
                ('paragraph_text', models.CharField(max_length=1000)),
                ('button_label', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='banner',
            name='button_label',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('involved_speltakken', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='content.speltak')),
            ],
        ),
    ]
