# Generated by Django 4.2.7 on 2025-04-10 18:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_footer_huurinfo_scoutingappinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaitem',
            name='date',
            field=models.DateField(default=datetime.date(2025, 4, 10)),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='involved_speltakken',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.speltak'),
        ),
    ]
