# Generated by Django 4.2.7 on 2025-04-10 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_agendaitem_date_alter_agendaitem_involved_speltakken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaitem',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
