# Generated by Django 4.2.7 on 2025-04-10 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_agendaitem_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendaitem',
            name='involved_speltakken',
        ),
    ]
