# Generated by Django 4.2.7 on 2025-04-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_remove_agendaitem_involved_speltakken'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaitem',
            name='involved_speltakken',
            field=models.ManyToManyField(to='content.speltak'),
        ),
    ]
