# Generated by Django 4.2.7 on 2025-06-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_agendaitem_involved_speltakken'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image1',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='banner',
            name='image1_alt_text',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='banner',
            name='image2',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='banner',
            name='image2_alt_text',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='banner',
            name='image3',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='banner',
            name='image3_alt_text',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='banner',
            name='image4',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='banner',
            name='image4_alt_text',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='banner',
            name='image5',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='banner',
            name='image5_alt_text',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='footer',
            name='huishoudelijk_regelement',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='huurinfo',
            name='image1',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='huurinfo',
            name='image1_alt_text',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='huurinfo',
            name='image2',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='huurinfo',
            name='image2_alt_text',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='huurinfo',
            name='image3',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='huurinfo',
            name='image3_alt_text',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='scoutingappinfo',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='scoutingappinfo',
            name='image_alt_text',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='speltak',
            name='thumbnail',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='speltak',
            name='thumbnail_alt_text',
            field=models.CharField(default='', max_length=255),
        ),
    ]
