# Generated by Django 4.2.7 on 2025-08-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_banner_image1_banner_image1_alt_text_banner_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='nudge_text',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image1',
            field=models.ImageField(default='', upload_to='image_uploads/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image2',
            field=models.ImageField(default='', upload_to='image_uploads/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image3',
            field=models.ImageField(default='', upload_to='image_uploads/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image4',
            field=models.ImageField(default='', upload_to='image_uploads/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image5',
            field=models.ImageField(default='', upload_to='image_uploads/'),
        ),
        migrations.AlterField(
            model_name='huurinfo',
            name='image1',
            field=models.ImageField(default='', upload_to='image_uploads/'),
        ),
        migrations.AlterField(
            model_name='huurinfo',
            name='image2',
            field=models.ImageField(default='', upload_to='image_uploads/'),
        ),
        migrations.AlterField(
            model_name='huurinfo',
            name='image3',
            field=models.ImageField(default='', upload_to='image_uploads/'),
        ),
        migrations.AlterField(
            model_name='scoutingappinfo',
            name='image',
            field=models.ImageField(default='', upload_to='image_uploads/'),
        ),
        migrations.AlterField(
            model_name='scoutingappinfo',
            name='image_alt_text',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='speltak',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='image_uploads/'),
        ),
    ]
