# Generated by Django 4.2.7 on 2025-09-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_banner_nudge_text_alter_banner_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='facebook_button_link',
            field=models.CharField(default='', max_length=9999),
        ),
        migrations.AddField(
            model_name='footer',
            name='instagram_button_link',
            field=models.CharField(default='', max_length=9999),
        ),
    ]
