# Generated by Django 4.2.7 on 2025-09-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_footer_facebook_button_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='huishoudelijk_regelement',
            field=models.FileField(default='', upload_to='file_uploads/'),
        ),
    ]
