# Generated by Django 4.2.7 on 2025-09-23 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_alter_footer_huishoudelijk_regelement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='facebook_button_label',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='instagram_button_label',
        ),
    ]
