# Generated by Django 4.2.7 on 2025-09-23 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_remove_footer_facebook_button_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='contact_button_label',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='huishoudelijk_regelement_button_label',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='privacybeleid_button_label',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='verhuur_button_label',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='vrienden_button_label',
        ),
    ]
