# Generated by Django 4.2.7 on 2025-10-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_remove_footer_contact_button_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoutingappinfo',
            name='button_label',
        ),
        migrations.RemoveField(
            model_name='scoutingappinfo',
            name='paragraph_text',
        ),
        migrations.AddField(
            model_name='scoutingappinfo',
            name='home_button_label',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='scoutingappinfo',
            name='home_image',
            field=models.ImageField(default='', upload_to='image_uploads/'),
        ),
        migrations.AddField(
            model_name='scoutingappinfo',
            name='home_image_alt_text',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='scoutingappinfo',
            name='home_image_caption',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='scoutingappinfo',
            name='home_paragraph_text',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='scoutingappinfo',
            name='home_title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='scoutingappinfo',
            name='paragraph_1_text',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='scoutingappinfo',
            name='paragraph_2_text',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='scoutingappinfo',
            name='paragraph_2_title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='scoutingappinfo',
            name='image_caption',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='scoutingappinfo',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
