# Generated by Django 4.2.7 on 2025-10-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_remove_scoutingappinfo_button_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huurinfo',
            name='button_label',
        ),
        migrations.RemoveField(
            model_name='huurinfo',
            name='paragraph_text',
        ),
        migrations.AddField(
            model_name='huurinfo',
            name='home_button_label',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='huurinfo',
            name='home_image1',
            field=models.ImageField(default='', upload_to='image_uploads/'),
        ),
        migrations.AddField(
            model_name='huurinfo',
            name='home_image1_alt_text',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='huurinfo',
            name='home_image2',
            field=models.ImageField(default='', upload_to='image_uploads/'),
        ),
        migrations.AddField(
            model_name='huurinfo',
            name='home_image2_alt_text',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='huurinfo',
            name='home_image3',
            field=models.ImageField(default='', upload_to='image_uploads/'),
        ),
        migrations.AddField(
            model_name='huurinfo',
            name='home_image3_alt_text',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='huurinfo',
            name='home_paragraph_text',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='huurinfo',
            name='home_title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='huurinfo',
            name='paragraph_1_text',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='huurinfo',
            name='paragraph_2_text',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='huurinfo',
            name='paragraph_2_title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='huurinfo',
            name='paragraph_3_text',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='huurinfo',
            name='paragraph_3_title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='huurinfo',
            name='paragraph_4_text',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='huurinfo',
            name='paragraph_4_title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='huurinfo',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
