# Generated by Django 4.2.7 on 2025-10-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_remove_huurinfo_button_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='huurinfo',
            name='verhuur_verantwoordelijke',
            field=models.ManyToManyField(to='content.leidinglid'),
        ),
    ]
